 name: 'Components Library CI'
 on:
    push:
    pull_request:
 jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       with:
            fetch-depth: 0
     - name: Use Node
       uses: actions/setup-node@v2
       with:
        node-version: 'v20.12.1'

     - name: Install dependencies
       run: npm install

     - name: Run Tests
       run: npm run test

     - name: Build Storybook
       run: npm run build-storybook
       
     - name: Publish Storybook
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
         publish_dir: ./storybook-static
         publish_branch: gh-pages
     
     - name: Extract version
       run: bash extract_version.sh
 
     - name: Get published version from npm
       id: get_published_version
       run: |
        PUBLISHED_VERSION=$(npm show $(node -p -e "require('./package.json').name") version || echo '0.0.0')
        echo "PUBLISHED_VERSION=$PUBLISHED_VERSION" >> $GITHUB_ENV
 
     - name: Check if version is updated
       id: check_version
       run: |
        VERSION=$(node -p -e "require('./package.json').version")
        SHOULD_PUBLISH=$(node -e "const semver = require('semver'); process.stdout.write(semver.gt(process.env.VERSION, process.env.PUBLISHED_VERSION));")
        echo "SHOULD_PUBLISH=$SHOULD_PUBLISH" >> $GITHUB_ENV
 
     - name: Config npm for publishing
       if: env.SHOULD_PUBLISH == 'true'
       run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
 
     - name: Build the package
       if: env.SHOULD_PUBLISH == 'true'
       run: npm run build
 
     - name: Publish to npm
       if: env.SHOULD_PUBLISH == 'true'
       run: npm publish --access public
       env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}