 name: 'Components Library CI'
 on:
    push:
    pull_request:
 jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       with:
            fetch-depth: 0
     - name: Use Node
       uses: actions/setup-node@v2
       with:
        node-version: 'v20.12.1'

     - name: Install dependencies
       run: npm install

     - name: Run Tests
       run: npm run test

     - name: Build Storybook
       run: npm run build-storybook
       
     - name: Publish Storybook
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
         publish_dir: ./storybook-static
         publish_branch: gh-pages
     
     - name: Get current version from package.json
       id: get_version
       run: echo "::set-output name=version::$(node -p -e \"require('./package.json').version\")"
 
     - name: Get published version from npm
       id: get_published_version
       run: echo "::set-output name=published_version::$(npm show $(node -p -e \"require('./package.json').name\") version || echo '0.0.0')"
 
     - name: Check if version is updated
       id: check_version
       run: echo "::set-output name=should_publish::$(node -p -e \"require('semver').gt('${{ steps.get_version.outputs.version }}', '${{ steps.get_published_version.outputs.published_version }}')\")"
 
     - name: Config npm for publishing
       if: steps.check_version.outputs.should_publish == 'true'
       run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
 
     - name: Build the package
       if: steps.check_version.outputs.should_publish == 'true'
       run: npm run build
 
     - name: Publish to npm
       if: steps.check_version.outputs.should_publish == 'true'
       run: npm publish --access public
       env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}