 name: 'Components Library CI'
 on:
    push:
    pull_request:
 jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       with:
            fetch-depth: 0
     - name: Use Node
       uses: actions/setup-node@v2
       with:
        node-version: 'v20.12.1'

     - name: Install dependencies
       run: npm install

     - name: Run Tests
       run: npm run test

     - name: Build Storybook
       run: npm run build-storybook
       
     - name: Publish Storybook
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
         publish_dir: ./storybook-static
         publish_branch: gh-pages